### PR TITLE
Load all members of child relations

### PR DESCRIPTION
**Pull request by PeterDRS**
That would support master routes that are built from child routes.

### CODE REVIEW

**Comment by sb12** [comment]
@PeterDRS could you give an example relation where this is needed, so that I can test how this works.

**Comment by PeterDRS** [comment]
I started building big train routes from small pieces. The advantage is to only maintain the small pieces, not always the big route. Also it saves space if the small pieces are not stored for every single train route of Germany.

Example: 5421651

**Comment by Nakaner** [comment]
@PeterDRS It is a consensus among public transport mappers in Germany not to use route segments. It is part of PTv1 and not PTv2. Please map as PTv2-conform as possible!

**Comment by PeterDRS** [comment]
Oh! I didn't know that. Unfortunately it is too late now.

Why not supporting route segments? You always know where the segment belongs to, it could also belong to many routes.

The stops could be encoded in master route.

**Comment by PeterDRS** [comment]
When having segments between all big stations in Germany it is only an act of 2-3 minutes to create nearly all train routes that exist.

With the old scheme it is always 1 hour to spend.

**Comment by Nakaner** [comment]
Please write your own public transport proposal (call it PTv3-PeterDRS, I will call my proposal PTv3-Nakaner) and present it [at the German Forum](http://forum.openstreetmap.org/viewtopic.php?id=30070) and [Talk-Transit mailing list](https://lists.openstreetmap.org/listinfo/talk-transit). Please also read [a posting](http://forum.openstreetmap.org/viewtopic.php?pid=462498#p462498) by the founder and maintainer of the Overpass API, especially section e.

**Comment by PeterDRS** [comment]
Ok, I have an advice: There are little pieces of sub-relations and one person, for example @Nakaner, uses his spare time merging the sub-pieces to a big one.

When I do a change in lets say Riesa, I request @Nakaner to change all 23 relations made from my subrelation.

I have 2 minutes time spent, an @Nakaner needs 2 days. But he is satisfied. :)

**Comment by PeterDRS** [comment]
Section e) says that it is uncomfortable to edit.

That's nonsense. It is uncomfortable to edit 6 relations when changing 1 thing on a track.

Of course it is not good to have to little peaces, e.g. one piece for every station->station section. That would be too small. But for big distances it is ok.

**Comment by sb12** [comment]
@PeterDRS OK I see what you mean. This needs a bit more code changes to work. 
As this seems not to be a widely accepted method to map, I do currently not want to support this method. To support it I would like to have at least some documentation and an approved proposal.
Even though I know that most of the railway tags have never seen a formal proposal, I think as this method might affect a lot of applications and there has been an accepted PT transport proposal (often called PTv2), here an accepted proposal is needed. 
In my opinion it doesn't make sense to support "exotic" alternative tagging/mapping schemes/methods that are only used by a few users as this will lead to mapping for the tool and therefore might break other tools/renderers.

Feel free to help working on PTv3 and whatever the outcome of v3 will be will probably be supported by my tool, if not I'm happy to have a new bug or pull request opened.
I will therefore close this for now.

@PeterDRS, @Nakaner: This is not the right place for tagging discussions.

**Comment by PeterDRS** [comment]
I'm sorry, I don't see that it is FORBIDDEN to do such combinations.

Question: Have you tested my code change? Has it worked?

**Comment by PeterDRS** [comment]
check this it should work with the ">>" instead of ">":

http://overpass-turbo.eu/s/aQv

**Comment by sb12** [comment]
> I'm sorry, I don't see that it is FORBIDDEN to do such combinations.

From http://wiki.openstreetmap.org/wiki/Proposed_features/Public_Transport#Route :
> After all the stops all the used ways should be inserted into the relation with an empty role. The ways should be inserted beginning with the way at the initial stop position and ending with the way at the terminal stop position. 

So, according to the accepted proposal only ways are allowed.

> Question: Have you tested my code change? Has it worked?

The overpass api request works, but that's not all that is needed.
Current code works like this:
1. get relation (including all ways and nodes) and parent relation from overpass
2. get all tags from relations that are either type=route or type=route_master
3. save all ways and nodes from relation with the requested id to work with them later
4. check whether a correct 'route=*' value is set.

So with your relation 3. fails because there are no ways in the relation and 4. fails because there's only a 'route_master=\*' and no 'route=*'

Anyway as I said above I'm not willing to support alternative controversial mapping methods.

**Comment by PeterDRS** [comment]
Oh my god it is a crime to put 4 relations in a parent relation and saying: "That is a route consisting of 4 sub-routes".

So I wonder how you go per train in reality! Do you only use trains going through or are you changing?

I think 3. could be changed to use all ways, not only the ones with a special id.

**Pull request closed without merging**
